/**
 * God roll definitions sourced from the TRUE Gaming D1 guides:
 *   PvP: https://truegaming.boards.net/thread/433/god-roll-pvp-guide
 *   PvE: https://truegaming.boards.net/thread/437/god-roll-pve-guide
 *
 * Structure per entry:
 *   col1, col2, col3, col4 — arrays of acceptable perk names for that column.
 *   A weapon passes a column if ANY of the listed perks is present on the item.
 *   A weapon is a "god roll" if it passes ALL four columns.
 *   A weapon is "close" if it passes at least CLOSE_THRESHOLD columns (default 3).
 *
 * Perk name matching is case-insensitive and trims whitespace.
 */

// How many columns must match to be considered "close" (but not god roll).
export const CLOSE_THRESHOLD = 3;

// ---------------------------------------------------------------------------
// PvP God Rolls
// ---------------------------------------------------------------------------
export const PVP = {
  // Scout Rifles
  "Angel's Advocate":      { col1: ["Reflex"], col2: ["Life Support", "Zen Moment"], col3: ["Perfect Balance"], col4: ["Hidden Hand"] },
  "Badger CCL":            { col1: ["Red Dot-OAS"], col2: ["Crowd Control"], col3: ["Hand-laid Stock"], col4: ["Hidden Hand"] },
  "Burning Eye":           { col1: ["Accurized Ballistics"], col2: ["Smallbore"], col3: ["Explosive Rounds"], col4: ["Third Eye", "Zen Moment"] },
  "Cocytus SR4":           { col1: ["Torch HS2"], col2: ["Life Support"], col3: ["Hand-laid Stock"], col4: ["Eye of the Storm"] },
  "Colovance's Duty":      { col1: ["Red Dot-OAS"], col2: ["Crowd Control"], col3: ["Hand-laid Stock"], col4: ["Hidden Hand"] },
  "Cryptic Dragon":        { col1: ["Red Dot-OAS"], col2: ["Crowd Control"], col3: ["Braced Frame"], col4: ["Reactive Reload"] },
  "The Distant Star":      { col1: ["Iron Ranged Scope"], col2: ["Perfect Balance"], col3: ["High Caliber Rounds"], col4: ["Zen Moment", "Hidden Hand"] },
  "Hand of Judgement":     { col1: ["Red Dot-OAS"], col2: ["Hand-laid Stock"], col3: ["High Caliber Rounds", "Explosive Rounds"], col4: ["Hidden Hand", "Zen Moment"] },
  "The Hero Formula":      { col1: ["Reflex"], col2: ["Life Support", "Zen Moment"], col3: ["Braced Frame"], col4: ["Hidden Hand"] },
  "Keystone 01":           { col1: ["Reflex"], col2: ["High Caliber Rounds", "Explosive Rounds"], col3: ["Perfect Balance"], col4: ["Hidden Hand"] },
  "Lethe Noblesse":        { col1: ["Reflex"], col2: ["Crowd Control"], col3: ["Hand-laid Stock"], col4: ["Hidden Hand"] },
  "NL Shadow 701X":        { col1: ["Red Dot-OAS"], col2: ["Zen Moment"], col3: ["Explosive Rounds"], col4: ["Hidden Hand"] },
  "Not Like the Others":   { col1: ["Reflex"], col2: ["Zen Moment"], col3: ["High Caliber Rounds"], col4: ["Hidden Hand"] },
  "The Saterienne Rapier": { col1: ["Red Dot-OAS"], col2: ["Crowd Control"], col3: ["Explosive Rounds"], col4: ["Reactive Reload"] },
  "SUROS DIS-43":          { col1: ["SPO-28"], col2: ["Perfect Balance", "Hammer Forged"], col3: ["Hidden Hand"], col4: ["Smallbore", "Hand-laid Stock"] },
  "SUROS DIS-47":          { col1: ["SPO-28"], col2: ["Perfect Balance", "Hammer Forged"], col3: ["Full Auto"], col4: ["Smallbore", "Hand-laid Stock"] },
  "Treads Upon Stars":     { col1: ["Red Dot-OAS"], col2: ["Crowd Control"], col3: ["Braced Frame"], col4: ["Hidden Hand"] },
  "Tuonela SR4":           { col1: ["Torch HS2"], col2: ["Life Support"], col3: ["Extended Mag"], col4: ["Zen Moment", "Third Eye"] },
  "The Wounded":           { col1: ["Reflex"], col2: ["High Caliber Rounds", "Explosive Rounds"], col3: ["Perfect Balance"], col4: ["Hidden Hand"] },

  // Pulse Rifles
  "Aegis of the Reef":     { col1: ["Red Dot-OAS", "SureShot IS"], col2: ["Perfect Balance"], col3: ["High Caliber Rounds"], col4: ["Counterbalance"] },
  "Apple of Discord":      { col1: ["SC Holo"], col2: ["Headseeker"], col3: ["Counterbalance"], col4: ["Hand-laid Stock"] },
  "Blind Perdition":       { col1: ["Smooth Ballistics", "Smart Drift Control"], col2: ["Hand-laid Stock", "Smallbore"], col3: ["High Caliber Rounds", "Hand Loaded"], col4: ["Outlaw", "Counterbalance"] },
  "B-29 Party Favor":      { col1: ["Reflex"], col2: ["Feeding Frenzy"], col3: ["Perfect Balance", "Hand-laid Stock"], col4: ["Counterbalance", "Rangefinder"] },
  "The Clever Dragon":     { col1: ["Iron Red Dot"], col2: ["Smallbore"], col3: ["High Caliber Rounds"], col4: ["Counterbalance"] },
  "Final Duty":            { col1: ["Reflex"], col2: ["Headseeker"], col3: ["Perfect Balance"], col4: ["Glass Half Full"] },
  "Grasp of Malok":        { col1: ["Red Dot-OAS"], col2: ["Counterbalance"], col3: ["Braced Frame", "Smallbore", "Perfect Balance"], col4: ["Glass Half Full"] },
  "Hawksaw":               { col1: ["SPO-28"], col2: ["Perfect Balance"], col3: ["Counterbalance"], col4: ["Rifled Barrel"] },
  "Herja-D":               { col1: ["SC Holo"], col2: ["Headseeker"], col3: ["Counterbalance"], col4: ["Hand-laid Stock"] },
  "Hopscotch Pilgrim":     { col1: ["Red Dot-OAS"], col2: ["Headseeker"], col3: ["Perfect Balance"], col4: ["Third Eye", "Glass Half Full"] },
  "Lyudmila-D":            { col1: ["SC Holo"], col2: ["Headseeker"], col3: ["Counterbalance"], col4: ["Hand-laid Stock"] },
  "Nirwen's Mercy":        { col1: ["Red Dot-OAS"], col2: ["Counterbalance"], col3: ["Braced Frame"], col4: ["Glass Half Full"] },
  "Parthian Shot":         { col1: ["Reflex"], col2: ["Feeding Frenzy"], col3: ["Hand-laid Stock"], col4: ["Headseeker"] },
  "Spare Change .25":      { col1: ["Red Dot-OAS"], col2: ["Counterbalance"], col3: ["Braced Frame"], col4: ["Glass Half Full"] },
  "SUROS PDX-41":          { col1: ["SPO-28"], col2: ["Perfect Balance"], col3: ["Hidden Hand"], col4: ["Smallbore"] },
  "SUROS PDX-45":          { col1: ["SPO-28"], col2: ["Perfect Balance"], col3: ["Counterbalance"], col4: ["Rifled Barrel", "Smallbore"] },
  "The Villainy":          { col1: ["Red Dot-OAS"], col2: ["Counterbalance"], col3: ["Braced Frame"], col4: ["Glass Half Full"] },
  "The Waltz":             { col1: ["Reflex"], col2: ["High Caliber Rounds"], col3: ["Smallbore"], col4: ["Counterbalance"] },

  // Hand Cannons
  "Byronic Hero":          { col1: ["SureShot IS", "TrueSight IS"], col2: ["Rangefinder"], col3: ["Rifled Barrel"], col4: ["Hidden Hand"] },
  "The Devil You Know":    { col1: ["SureShot IS", "TrueSight IS"], col2: ["Rangefinder"], col3: ["Rifled Barrel"], col4: ["Icarus"] },
  "Down and Doubt 00-0":   { col1: ["SureShot IS", "TrueSight IS"], col2: ["Luck in the Chamber"], col3: ["Rifled Barrel"], col4: ["Icarus"] },
  "Exile's Student":       { col1: ["Accurized Ballistics"], col2: ["Hammer Forged"], col3: ["Explosive Rounds"], col4: ["Hidden Hand"] },
  "Eyasluna":              { col1: ["SureShot IS", "TrueSight IS"], col2: ["Rangefinder"], col3: ["Rifled Barrel"], col4: ["Hidden Hand"] },
  "Finnala's Peril":       { col1: ["SureShot IS", "TrueSight IS"], col2: ["Rangefinder"], col3: ["Rifled Barrel"], col4: ["Hidden Hand"] },
  "Free Will III":         { col1: ["SureShot IS", "TrueSight IS"], col2: ["Explosive Rounds"], col3: ["Hammer Forged"], col4: ["Rangefinder"] },
  "Gatheris-D":            { col1: ["SureShot IS", "TrueSight IS"], col2: ["Crowd Control"], col3: ["Rangefinder"], col4: ["Reinforced Barrel"] },
  "Her Revenge":           { col1: ["SureShot IS", "TrueSight IS"], col2: ["Rangefinder"], col3: ["Rifled Barrel"], col4: ["Hidden Hand", "Icarus"] },
  "How Dare You":          { col1: ["SureShot IS", "TrueSight IS"], col2: ["Icarus"], col3: ["Rifled Barrel"], col4: ["Rangefinder"] },
  "Ill Will":              { col1: ["SureShot IS"], col2: ["Rangefinder"], col3: ["Braced Frame"], col4: ["Luck in the Chamber"] },
  "Imago Loop":            { col1: ["SureShot IS", "TrueSight IS"], col2: ["Rangefinder"], col3: ["Rifled Barrel"], col4: ["Hidden Hand", "Icarus"] },
  "Imago Loop (Fatebringer Roll)": { col1: ["SureShot IS", "TrueSight IS"], col2: ["Outlaw"], col3: ["Explosive Rounds"], col4: ["Firefly"] },
  "Judith-D":              { col1: ["SureShot IS", "TrueSight IS"], col2: ["Crowd Control"], col3: ["Final Round", "Reactive Reload"], col4: ["Speed Reload"] },
  "Kumakatok HC-4":        { col1: ["SureShot IS", "TrueSight IS"], col2: ["Luck in the Chamber"], col3: ["Braced Frame"], col4: ["Icarus"] },
  "The Lingering Song":    { col1: ["Iron Lordly Sights"], col2: ["Braced Frame"], col3: ["Feather Mag"], col4: ["Luck in the Chamber"] },
  "Lord High Fixer":       { col1: ["SureShot IS", "TrueSight IS"], col2: ["Rangefinder"], col3: ["Rifled Barrel"], col4: ["Hidden Hand", "Icarus"] },
  "The Palindrome":        { col1: ["SureShot IS", "TrueSight IS"], col2: ["Icarus"], col3: ["Rifled Barrel"], col4: ["Rangefinder"] },
  "The Revelator":         { col1: ["SureShot IS", "TrueSight IS"], col2: ["Rangefinder"], col3: ["Rifled Barrel"], col4: ["Hidden Hand"] },
  "Stolen Pride":          { col1: ["TrueSight IS"], col2: ["Rifled Barrel"], col3: ["Explosive Rounds"], col4: ["Rangefinder"] },
  "The Vanity":            { col1: ["SureShot IS", "TrueSight IS"], col2: ["Luck in the Chamber"], col3: ["Rifled Barrel"], col4: ["Icarus"] },
  "Uffren HC4":            { col1: ["SureShot IS", "TrueSight IS"], col2: ["Luck in the Chamber"], col3: ["Rifled Barrel"], col4: ["Icarus"] },
  "The Wail":              { col1: ["SureShot IS", "TrueSight IS"], col2: ["Outlaw"], col3: ["Hammer Forged"], col4: ["Rangefinder"] },

  // Auto Rifles
  "An Answering Chord":    { col1: ["SPO-28"], col2: ["Perfect Balance"], col3: ["Smallbore"], col4: ["Rangefinder"] },
  "Antipodal Hindsight":   { col1: ["Reflex"], col2: ["Rangefinder"], col3: ["Rifled Barrel"], col4: ["Hidden Hand"] },
  "Arminius-D":            { col1: ["SC Holo"], col2: ["High Caliber Rounds"], col3: ["Counterbalance"], col4: ["Braced Frame"] },
  "Assembly II":           { col1: ["Reflex"], col2: ["High Caliber Rounds"], col3: ["Perfect Balance"], col4: ["Counterbalance"] },
  "The Continental":       { col1: ["Reflex"], col2: ["Crowd Control"], col3: ["Braced Frame"], col4: ["Counterbalance"] },
  "The Dealbreaker":       { col1: ["SC Holo"], col2: ["Crowd Control"], col3: ["Rangefinder"], col4: ["Rifled Barrel"] },
  "Doctrine of Passing":   { col1: ["FastDraw IS"], col2: ["Persistence"], col3: ["Braced Frame"], col4: ["Counterbalance"] },
  "Does Not Bow":          { col1: ["Red Dot-OAS"], col2: ["Rangefinder"], col3: ["Perfect Balance"], col4: ["Hidden Hand"] },
  "Extremophile 011":      { col1: ["Reflex"], col2: ["High Caliber Rounds"], col3: ["Perfect Balance"], col4: ["Counterbalance"] },
  "Grim Citizen III":      { col1: ["Red Dot-OAS"], col2: ["Rangefinder"], col3: ["Perfect Balance"], col4: ["Hidden Hand"] },
  "Haakon's Hatchet":      { col1: ["Red Dot-OAS"], col2: ["Rangefinder"], col3: ["Smallbore"], col4: ["Counterbalance"] },
  "Her Memory":            { col1: ["Reflex", "Sureshot IS"], col2: ["Rangefinder"], col3: ["Perfect Balance"], col4: ["Counterbalance"] },
  "Hex Caster ARC":        { col1: ["Red Dot-OAS"], col2: ["Persistence"], col3: ["Perfect Balance"], col4: ["Life Support"] },
  "Paleocontact JPK-43":   { col1: ["Reflex"], col2: ["Rangefinder"], col3: ["Rifled Barrel"], col4: ["Counterbalance"] },
  "Red Spectre":           { col1: ["Red Dot-OAS"], col2: ["Rangefinder"], col3: ["Perfect Balance"], col4: ["Hidden Hand"] },
  "Shadow Price":          { col1: ["Red Dot-OAS"], col2: ["Rangefinder"], col3: ["Perfect Balance"], col4: ["Hidden Hand"] },
  "Soulstealer's Claw":    { col1: ["Red Dot-OAS"], col2: ["Perfect Balance"], col3: ["Single Point Sling"], col4: ["Counterbalance"] },
  "SUROS ARI-41":          { col1: ["SPO-28"], col2: ["Perfect Balance"], col3: ["Rifled Barrel"], col4: ["Counterbalance"] },
  "SUROS ARI-45":          { col1: ["SPO-28"], col2: ["Perfect Balance"], col3: ["Rifled Barrel"], col4: ["Counterbalance"] },
  "The Unbent Tree":       { col1: ["Iron Ranged Scope"], col2: ["Braced Frame"], col3: ["Single Point Sling"], col4: ["Counterbalance"] },
  "Vision Stone":          { col1: ["Smart Drift Control"], col2: ["Send It"], col3: ["Hand Loaded"], col4: ["Crowd Control"] },
  "Zarinaea-D":            { col1: ["SC Holo"], col2: ["Crowd Control"], col3: ["Rangefinder"], col4: ["Braced Frame"] },
  "Zero-Day Dilemma":      { col1: ["Reflex"], col2: ["Crowd Control"], col3: ["Perfect Balance"], col4: ["Hidden Hand"] },

  // Sniper Rifles
  "1000 Yard Stare":       { col1: ["ShortGaze SLH10"], col2: ["Eye of the Storm"], col3: ["Quickdraw"], col4: ["Hidden Hand"] },
  "20/20 AMR7":            { col1: ["ShortGaze SLH10"], col2: ["Unflinching"], col3: ["Skip Rounds"], col4: ["Hidden Hand"] },
  "Antinomy XVI":          { col1: ["ATA Scout"], col2: ["Unflinching"], col3: ["Performance Bonus"], col4: ["Quickdraw"] },
  "Aoife Rua-D":           { col1: ["ATA Scout"], col2: ["Unflinching"], col3: ["Performance Bonus"], col4: ["Quickdraw"] },
  "Bitter Edge 010":       { col1: ["ShortGaze SLH10"], col2: ["Quickdraw"], col3: ["Life Support"], col4: ["Hidden Hand"] },
  "But Not Forgotten":     { col1: ["Linear Compensator"], col2: ["Braced Frame"], col3: ["Quickdraw"], col4: ["Hidden Hand"] },
  "Deposition VII":        { col1: ["ShortGaze SLH10"], col2: ["Snapshot"], col3: ["Mulligan"], col4: ["Unflinching"] },
  "Devil's Dawn":          { col1: ["Linear Compensator"], col2: ["Life Support"], col3: ["Quickdraw"], col4: ["Firefly"] },
  "Eirene RR4":            { col1: ["Faucon SS1"], col2: ["Performance Bonus"], col3: ["Quickdraw"], col4: ["Unflinching"] },
  "Event Horizon":         { col1: ["ShortGaze SLH10"], col2: ["Grenadier", "Spray and Pray"], col3: ["Smallbore"], col4: ["Hidden Hand"] },
  "Extrasolar RR4":        { col1: ["ShortGaze SLH10"], col2: ["Eye of the Storm"], col3: ["Quickdraw"], col4: ["Hidden Hand"] },
  "Her Fury":              { col1: ["ShortGaze SLH10"], col2: ["Life Support"], col3: ["Quickdraw"], col4: ["Hidden Hand"] },
  "The Laughing Heart":    { col1: ["Linear Compensator"], col2: ["Injection Mold"], col3: ["Quickdraw"], col4: ["Hidden Hand"] },
  "LDR 5001":              { col1: ["ShortGaze SLH10"], col2: ["Life Support"], col3: ["Quickdraw"], col4: ["Hidden Hand"] },
  "Seventh Sense":         { col1: ["ViewTac SLH20", "Ambush SLH25"], col2: ["Grenadier"], col3: ["Quickdraw"], col4: ["Firefly"] },
  "Tamar-D":               { col1: ["ATA Scout"], col2: ["Unflinching"], col3: ["Performance Bonus"], col4: ["Quickdraw"] },
  "Tao Hua Yuan":          { col1: ["ShortGaze SLH10"], col2: ["Eye of the Storm"], col3: ["Quickdraw"], col4: ["Hidden Hand"] },
  "Uzume RR4":             { col1: ["Faucon SS1"], col2: ["Performance Bonus"], col3: ["Quickdraw"], col4: ["Unflinching"] },
  "Weyloran's March":      { col1: ["ShortGaze SLH10"], col2: ["Eye of the Storm"], col3: ["Quickdraw"], col4: ["Hidden Hand"] },
  "Y-09 Longbow Synthesis":{ col1: ["ShortGaze SLH10"], col2: ["Life Support"], col3: ["Quickdraw"], col4: ["Hidden Hand"] },

  // Shotguns
  "44 Curtain Call":       { col1: ["Linear Compensator", "Accurized Ballistics", "Field Choke"], col2: ["Performance Bonus"], col3: ["Reinforced Barrel", "Rifled Barrel"], col4: ["Rangefinder"] },
  "Bad Counsel IV":        { col1: ["Aggressive Ballistics"], col2: ["Close and/or Personal", "Close and Personal"], col3: ["Quickdraw", "Snapshot"], col4: ["Rangefinder"] },
  "Burden of Proof XI":    { col1: ["Linear Compensator", "Accurized Ballistics", "Field Choke"], col2: ["Rangefinder"], col3: ["Reinforced Barrel", "Rifled Barrel"], col4: ["Performance Bonus"] },
  "The Comedian":          { col1: ["Linear Compensator", "Accurized Ballistics", "Field Choke"], col2: ["Full Auto"], col3: ["Reinforced Barrel", "Rifled Barrel"], col4: ["Performance Bonus"] },
  "Conspiracy Theory-D":   { col1: ["Field Choke"], col2: ["Rangefinder"], col3: ["Reinforced Barrel", "Rifled Barrel"], col4: ["Performance Bonus"] },
  "Her Champion":          { col1: ["Linear Compensator", "Accurized Ballistics", "Field Choke"], col2: ["Rangefinder"], col3: ["Reinforced Barrel", "Rifled Barrel"], col4: ["Performance Bonus"] },
  "Jingukogo-D":           { col1: ["Linear Compensator", "Accurized Ballistics", "Field Choke"], col2: ["Final Round"], col3: ["Rangefinder"], col4: ["Rifled Barrel"] },
  "Last-Ditch 001":        { col1: ["CQB Ballistics"], col2: ["Quickdraw"], col3: ["Hammer Forged"], col4: ["Rangefinder"] },
  "Matador 64":            { col1: ["Aggressive Ballistics"], col2: ["Full Auto"], col3: ["Reinforced Barrel", "Rifled Barrel"], col4: ["Rangefinder"] },
  "The Next Big Thing":    { col1: ["Linear Compensator", "Accurized Ballistics", "Field Choke"], col2: ["Rangefinder"], col3: ["Rifled Barrel"], col4: ["Close and/or Personal", "Close and Personal"] },
  "Occam's Razor":         { col1: ["Linear Compensator", "Accurized Ballistics", "Field Choke"], col2: ["Performance Bonus"], col3: ["Reinforced Barrel", "Rifled Barrel"], col4: ["Rangefinder"] },
  "Patch-A":               { col1: ["Linear Compensator", "Accurized Ballistics", "Field Choke"], col2: ["Rangefinder"], col3: ["Rifled Barrel"], col4: ["Close and/or Personal", "Close and Personal"] },
  "Party Crasher +1":      { col1: ["Aggressive Ballistics"], col2: ["Rangefinder"], col3: ["Rifled Barrel", "Reinforced Barrel"], col4: ["Performance Bonus"] },
  "The Proud Spire":       { col1: ["Linear Compensator"], col2: ["Reinforced Barrel", "Rifled Barrel"], col3: ["Quickdraw", "Snapshot"], col4: ["Rangefinder"] },
  "Stolen Will":           { col1: ["Linear Compensator", "Accurized Ballistics", "Field Choke"], col2: ["Rangefinder"], col3: ["Reinforced Barrel", "Rifled Barrel"], col4: ["Performance Bonus"] },
  "Strongbow-D":           { col1: ["Linear Compensator", "Accurized Ballistics", "Field Choke"], col2: ["Close and/or Personal", "Close and Personal"], col3: ["Rangefinder"], col4: ["Rifled Barrel"] },
  "Two to the Morgue":     { col1: ["Linear Compensator", "Accurized Ballistics", "Field Choke"], col2: ["Rangefinder"], col3: ["Reinforced Barrel", "Rifled Barrel"], col4: ["Performance Bonus"] },
  "Unraveling Thread":     { col1: ["CQB Ballistics"], col2: ["Hammer Forged"], col3: ["Hand Loaded"], col4: ["Rangefinder"] },
  "Winter's End":          { col1: ["Linear Compensator"], col2: ["Rifled Barrel"], col3: ["Lightweight"], col4: ["Life Support", "Performance Bonus"] },

  // Fusion Rifles
  "77 Wizard":             { col1: ["Red Dot-OAS"], col2: ["Rangefinder"], col3: ["Braced Frame", "Rifled Barrel"], col4: ["Grenadier"] },
  "Ashraven's Flight":     { col1: ["Red Dot-OAS"], col2: ["Hipfire"], col3: ["Braced Frame"], col4: ["Hot Swap"] },
  "The Branded Lord":      { col1: ["Linear Compensator"], col2: ["Braced Frame"], col3: ["Accelerated Coils"], col4: ["Rangefinder"] },
  "Darkblade's Spite":     { col1: ["Red Dot-OAS"], col2: ["Hidden Hand"], col3: ["Braced Frame", "Rifled Barrel"], col4: ["Rangefinder"] },
  "Each New Day":          { col1: ["Reflex"], col2: ["Unflinching"], col3: ["Snapshot", "Hand-laid Stock"], col4: ["Counterbalance"] },
  "Ex Astris":             { col1: ["Reflex"], col2: ["Hip Fire"], col3: ["Braced Frame"], col4: ["Hidden Hand"] },
  "Hitchhiker FR4":        { col1: ["Reflex"], col2: ["Hip Fire"], col3: ["Braced Frame"], col4: ["Hot Swap"] },
  "Long Far Gone":         { col1: ["Reflex"], col2: ["Hip Fire"], col3: ["Braced Frame"], col4: ["Hot Swap"] },
  "Phanta Rei":            { col1: ["Reflex"], col2: ["Hip Fire"], col3: ["Braced Frame"], col4: ["Hot Swap"] },
  "Saladin's Vigil":       { col1: ["Linear Compensator"], col2: ["Rifled Barrel"], col3: ["Quickdraw"], col4: ["Rangefinder"] },
  "Split Shifter Pro":     { col1: ["Red Dot-OAS"], col2: ["Hip Fire"], col3: ["Braced Frame"], col4: ["Hot Swap"] },
  "Techuen Rage":          { col1: ["SureShot IS", "Reflex"], col2: ["Hidden Hand"], col3: ["Braced Frame", "Rifled Barrel"], col4: ["Rangefinder"] },
  "Thesan FR4":            { col1: ["Torch HS2"], col2: ["Hot Swap"], col3: ["Braced Frame", "Accelerated Coils"], col4: ["Rangefinder"] },
  "The Vacancy":           { col1: ["Torch HS2"], col2: ["Hot Swap"], col3: ["Braced Frame"], col4: ["Rangefinder"] },
  "The Vortex":            { col1: ["Reflex"], col2: ["Hip Fire"], col3: ["Braced Frame"], col4: ["Hot Swap", "Hotswap"] },
  "The Waiting":           { col1: ["Reflex"], col2: ["Accelerated Coils"], col3: ["Perfect Balance", "Kneepads"], col4: ["Rangefinder"] },
  "Worlds to Come 001":    { col1: ["Reflex"], col2: ["Snapshot"], col3: ["Hammer Forged"], col4: ["Hidden Hand"] },

  // Sidearms
  "Anton's Rule":          { col1: ["SureShot IS", "TrueSight IS"], col2: ["Zen Moment"], col3: ["Hand Loaded"], col4: ["Rangefinder", "Hidden Hand"] },
  "The Binding Blaze":     { col1: ["Iron Lordly Sights"], col2: ["Hand Loaded", "Fitted Stock"], col3: ["High Caliber Rounds"], col4: ["Rangefinder", "Hidden Hand", "Zen Moment"] },
  "Conviction II":         { col1: ["SureShot IS", "TrueSight IS"], col2: ["Zen Moment"], col3: ["Hot Swap"], col4: ["High Caliber Rounds"] },
  "Crow's Eye":            { col1: ["Linear Compensator"], col2: ["Hand Loaded"], col3: ["High Caliber Rounds"], col4: ["Rangefinder"] },
  "Havoc Pigeon":          { col1: ["SureShot IS", "TrueSight IS"], col2: ["Zen Moment"], col3: ["Hot Swap"], col4: ["High Caliber Rounds"] },
  "Impeacher V":           { col1: ["SureShot IS", "TrueSight IS"], col2: ["High Caliber Rounds", "Quickdraw"], col3: ["Hand Loaded"], col4: ["Rangefinder", "Hidden Hand"] },
  "Ironwreath-D":          { col1: ["SureShot IS", "TrueSight IS"], col2: ["Zen Moment"], col3: ["Hot Swap"], col4: ["High Caliber Rounds"] },
  "JabberHakke-D":         { col1: ["SureShot IS", "TrueSight IS"], col2: ["Zen Moment"], col3: ["Hot Swap"], col4: ["High Caliber Rounds"] },
  "Teacup Tempest":        { col1: ["SureShot IS", "TrueSight IS"], col2: ["Zen Moment"], col3: ["High Caliber Rounds"], col4: ["Rangefinder"] },
  "Queen's Choice":        { col1: ["Linear Compensator"], col2: ["Rangefinder", "Zen Moment"], col3: ["High Caliber Rounds"], col4: ["Hot Swap"] },
  "The Wormwood":          { col1: ["SureShot IS", "TrueSight IS"], col2: ["High Caliber Rounds", "Quickdraw"], col3: ["Hand Loaded"], col4: ["Rangefinder", "Hidden Hand"] },

  // Machine Guns
  "Bane of the Taken":     { col1: ["Smooth Ballistics"], col2: ["Counterbalance"], col3: ["Perfect Balance"], col4: ["Hidden Hand"] },
  "Baron's Ambition":      { col1: ["Accurized Ballistics", "Linear Compensator"], col2: ["Counterbalance", "Life Support"], col3: ["Perfect Balance"], col4: ["Rangefinder", "Feeding Frenzy", "Hidden Hand", "Crowd Control"] },
  "Bonekruscher":          { col1: ["Linear Compensator"], col2: ["Feeding Frenzy"], col3: ["Quickdraw", "Hand-laid Stock"], col4: ["Crowd Control"] },
  "Bretomart's Stand":     { col1: ["Linear Compensator"], col2: ["Hip Fire"], col3: ["Rifled Barrel"], col4: ["Hidden Hand"] },
  "Chaotic Neutral":       { col1: ["Linear Compensator"], col2: ["Hip Fire"], col3: ["Rifled Barrel"], col4: ["Hidden Hand"] },
  "Diluvian 10/4X":        { col1: ["Linear Compensator"], col2: ["Hip Fire"], col3: ["Braced Frame"], col4: ["Persistence"] },
  "First Citizen IX":      { col1: ["Linear Compensator"], col2: ["Hip Fire"], col3: ["Perfect Balance"], col4: ["Persistence"] },
  "Ruin Wake":             { col1: ["Linear Compensator"], col2: ["Hip Fire"], col3: ["Rifled Barrel"], col4: ["Hidden Hand"] },
  "Objection IV":          { col1: ["Linear Compensator"], col2: ["Hip Fire"], col3: ["Rifled Barrel"], col4: ["Hidden Hand"] },
  "The Silvered Dread":    { col1: ["Linear Compensator"], col2: ["Perfect Balance"], col3: ["Field Scout"], col4: ["Hidden Hand"] },
  "The Swarm":             { col1: ["Linear Compensator"], col2: ["Life Support"], col3: ["Rifled Barrel"], col4: ["Rangefinder"] },
  "Unending Deluge III":   { col1: ["Linear Compensator"], col2: ["Counterbalance"], col3: ["Perfect Balance"], col4: ["Rangefinder"] },
  "The Variable":          { col1: ["Linear Compensator"], col2: ["Hip Fire"], col3: ["Braced Frame"], col4: ["Persistence"] },
  "Zombie Apocalypse WF47":{ col1: ["Linear Compensator", "Accurized Ballistics", "Field Choke"], col2: ["Life Support", "Counterbalance"], col3: ["Perfect Balance"], col4: ["Rangefinder", "Hidden Hand", "Feeding Frenzy"] },

  // Rocket Launchers
  "The Ash Factory":       { col1: ["Warhead Verniers", "Hard Launch"], col2: ["Tripod"], col3: ["Javelin"], col4: ["Grenades and Horseshoes"] },
  "Disassembly Required":  { col1: ["Warhead Verniers", "Hard Launch"], col2: ["Heavy Payload"], col3: ["Javelin"], col4: ["Grenades and Horseshoes"] },
  "The Nightmare":         { col1: ["Warhead Verniers", "Hard Launch"], col2: ["Tripod"], col3: ["Field Scout"], col4: ["Grenades and Horseshoes"] },
  "Something Wicked":      { col1: ["Soft Launch"], col2: ["Grenadier", "Last Resort"], col3: ["Field Scout"], col4: ["Cluster Bomb"] },
  "SUROS JLB-42":          { col1: ["Warhead Verniers", "Hard Launch"], col2: ["Heavy Payload"], col3: ["Grenades and Horseshoes"], col4: ["Javelin"] },
  "SUROS JLB-47":          { col1: ["Warhead Verniers", "Hard Launch"], col2: ["Heavy Payload"], col3: ["Grenades and Horseshoes"], col4: ["Javelin"] },
  "Steel Oracle Z-11":     { col1: ["Warhead Verniers", "Hard Launch"], col2: ["Tripod"], col3: ["Field Scout"], col4: ["Grenades and Horseshoes"] },
  "The Titanium Orchid":   { col1: ["Hard Launch", "Aggressive Launch"], col2: ["Heavy Payload"], col3: ["Speed Reload", "Flared Magwell"], col4: ["Grenades and Horseshoes"] },
  "Tormod's Bellows":      { col1: ["Warhead Verniers", "Hard Launch"], col2: ["Tripod"], col3: ["Heavy Payload"], col4: ["Grenades and Horseshoes"] },
  "Unto Dust 00":          { col1: ["Warhead Verniers", "Hard Launch"], col2: ["Field Scout"], col3: ["Heavy Payload"], col4: ["Grenades and Horseshoes"] },
  "The Vertigo":           { col1: ["Warhead Verniers", "Hard Launch"], col2: ["Heavy Payload"], col3: ["Grenades and Horseshoes"], col4: ["Javelin"] },
  "The Warpath":           { col1: ["Warhead Verniers", "Hard Launch"], col2: ["Field Scout"], col3: ["Javelin"], col4: ["Grenades and Horseshoes"] },
};

// ---------------------------------------------------------------------------
// PvE God Rolls
// ---------------------------------------------------------------------------
export const PVE = {
  // Scout Rifles
  "Angel's Advocate":      { col1: ["Reflex"], col2: ["Outlaw"], col3: ["High Caliber Rounds"], col4: ["Firefly"] },
  "Badger CCL":            { col1: ["Red Dot-OAS"], col2: ["Triple Tap"], col3: ["Field Scout"], col4: ["Army of One"] },
  "Burning Eye":           { col1: ["Accurized Ballistics"], col2: ["Smallbore"], col3: ["Explosive Rounds"], col4: ["Third Eye", "Zen Moment"] },
  "Cocytus SR4":           { col1: ["Torch HS2"], col2: ["Triple Tap"], col3: ["Extended Mag"], col4: ["Firefly"] },
  "Colovance's Duty":      { col1: ["Red Dot-OAS"], col2: ["Triple Tap"], col3: ["Field Scout"], col4: ["Firefly"] },
  "Cryptic Dragon":        { col1: ["Red Dot-OAS"], col2: ["Triple Tap"], col3: ["High Caliber Rounds"], col4: ["Firefly"] },
  "The Distant Star":      { col1: ["Iron Ranged Scope"], col2: ["Triple Tap"], col3: ["Perfect Balance"], col4: ["Extended Mag"] },
  "Hand of Judgement":     { col1: ["Red Dot-OAS"], col2: ["Perfect Balance"], col3: ["High Caliber Rounds"], col4: ["Firefly"] },
  "The Hero Formula":      { col1: ["Reflex"], col2: ["Outlaw"], col3: ["High Caliber Rounds"], col4: ["Firefly"] },
  "Keystone 01":           { col1: ["Reflex"], col2: ["Triple Tap"], col3: ["Extended Mag"], col4: ["Firefly"] },
  "Lethe Noblesse":        { col1: ["Reflex"], col2: ["Triple Tap"], col3: ["High Caliber Rounds"], col4: ["Army of One"] },
  "NL Shadow 701X":        { col1: ["Red Dot-OAS"], col2: ["Triple Tap"], col3: ["Field Scout"], col4: ["Army of One"] },
  "The Saterienne Rapier": { col1: ["Red Dot-OAS"], col2: ["Triple Tap"], col3: ["Field Scout"], col4: ["Army of One"] },
  "SUROS DIS-43":          { col1: ["SPO-28"], col2: ["High Caliber Rounds"], col3: ["Spray and Play"], col4: ["Speed Reload"] },
  "SUROS DIS-47":          { col1: ["SPO-28"], col2: ["High Caliber Rounds"], col3: ["Spray and Play"], col4: ["Speed Reload"] },
  "Treads Upon Stars":     { col1: ["Red Dot-OAS"], col2: ["Triple Tap"], col3: ["Field Scout"], col4: ["Army of One"] },
  "Tuonela SR4":           { col1: ["Torch HS2"], col2: ["Triple Tap"], col3: ["Extended Mag"], col4: ["Firefly"] },
  "The Wounded":           { col1: ["Reflex"], col2: ["Triple Tap"], col3: ["Extended Mag"], col4: ["Firefly"] },

  // Pulse Rifles
  "Aegis of the Reef":     { col1: ["Red Dot-OAS", "SureShot IS"], col2: ["Perfect Balance"], col3: ["High Caliber Rounds"], col4: ["Counterbalance"] },
  "Apple of Discord":      { col1: ["SC Holo"], col2: ["Headseeker"], col3: ["Counterbalance"], col4: ["Hand-laid Stock"] },
  "Blind Perdition":       { col1: ["Smooth Ballistics", "Smart Drift Control"], col2: ["Hand-laid Stock", "Smallbore"], col3: ["High Caliber Rounds", "Hand Loaded"], col4: ["Outlaw", "Counterbalance"] },
  "B-29 Party Favor":      { col1: ["Reflex"], col2: ["Feeding Frenzy"], col3: ["Perfect Balance"], col4: ["Headseeker"] },
  "The Clever Dragon":     { col1: ["Iron Red Dot"], col2: ["Smallbore"], col3: ["High Caliber Rounds"], col4: ["Counterbalance"] },
  "Final Duty":            { col1: ["Reflex"], col2: ["Counterbalance"], col3: ["Braced Frame"], col4: ["Feeding Frenzy"] },
  "Grasp of Malok":        { col1: ["Red Dot-OAS"], col2: ["Counterbalance"], col3: ["Braced Frame", "Smallbore", "Perfect Balance"], col4: ["Feeding Frenzy"] },
  "Hawksaw":               { col1: ["SPO-28"], col2: ["Perfect Balance"], col3: ["Counterbalance"], col4: ["Rifled Barrel"] },
  "Herja-D":               { col1: ["SC Holo"], col2: ["Headseeker"], col3: ["Counterbalance"], col4: ["Hand-laid Stock"] },
  "Hopscotch Pilgrim":     { col1: ["Red Dot-OAS"], col2: ["Headseeker"], col3: ["Perfect Balance"], col4: ["Feeding Frenzy"] },
  "Lyudmila-D":            { col1: ["SC Holo"], col2: ["Headseeker"], col3: ["Counterbalance"], col4: ["Hand-laid Stock"] },
  "Nirwen's Mercy":        { col1: ["Red Dot-OAS"], col2: ["Counterbalance"], col3: ["Braced Frame"], col4: ["Feeding Frenzy"] },
  "Parthian Shot":         { col1: ["Reflex"], col2: ["Feeding Frenzy"], col3: ["Hand-laid Stock"], col4: ["Headseeker"] },
  "Spare Change .25":      { col1: ["Red Dot-OAS"], col2: ["Counterbalance"], col3: ["Braced Frame"], col4: ["Feeding Frenzy"] },
  "SUROS PDX-41":          { col1: ["SPO-28"], col2: ["Perfect Balance"], col3: ["Counterbalance"], col4: ["Rifled Barrel", "Smallbore"] },
  "SUROS PDX-45":          { col1: ["SPO-28"], col2: ["Perfect Balance"], col3: ["Counterbalance"], col4: ["Rifled Barrel", "Smallbore"] },
  "The Villainy":          { col1: ["Red Dot-OAS"], col2: ["Counterbalance"], col3: ["Braced Frame"], col4: ["Feeding Frenzy"] },
  "The Waltz":             { col1: ["Reflex"], col2: ["Feeding Frenzy"], col3: ["High Caliber Rounds"], col4: ["Headseeker"] },

  // Hand Cannons
  "Byronic Hero":          { col1: ["SureShot IS", "TrueSight IS"], col2: ["Spray and Play"], col3: ["Extended Mag"], col4: ["Luck in the Chamber"] },
  "The Devil You Know":    { col1: ["SureShot IS", "TrueSight IS"], col2: ["Outlaw"], col3: ["Explosive Rounds"], col4: ["Luck in the Chamber"] },
  "Down and Doubt 00-0":   { col1: ["SureShot IS", "TrueSight IS"], col2: ["Luck in the Chamber"], col3: ["Extended Mag"], col4: ["Firefly"] },
  "Eyasluna":              { col1: ["SureShot IS", "TrueSight IS"], col2: ["Spray and Play"], col3: ["Extended Mag"], col4: ["Army of One"] },
  "Finnala's Peril":       { col1: ["SureShot IS", "TrueSight IS"], col2: ["Spray and Play"], col3: ["Extended Mag"], col4: ["Army of One"] },
  "Free Will III":         { col1: ["SureShot IS", "TrueSight IS"], col2: ["Outlaw"], col3: ["Explosive Rounds"], col4: ["Firefly"] },
  "Gatheris-D":            { col1: ["SureShot IS", "TrueSight IS"], col2: ["Army of One"], col3: ["Spray and Play"], col4: ["Speed Reload"] },
  "Her Revenge":           { col1: ["SureShot IS", "TrueSight IS"], col2: ["Spray and Play"], col3: ["Extended Mag"], col4: ["Army of One"] },
  "How Dare You":          { col1: ["SureShot IS", "TrueSight IS"], col2: ["Spray and Play"], col3: ["High Caliber Rounds"], col4: ["Luck in the Chamber"] },
  "Ill Will":              { col1: ["SureShot IS", "TrueSight IS"], col2: ["Outlaw"], col3: ["Extended Mag"], col4: ["Luck in the Chamber"] },
  "Imago Loop (Fatebringer Roll)": { col1: ["SureShot IS", "TrueSight IS"], col2: ["Outlaw"], col3: ["Explosive Rounds"], col4: ["Firefly"] },
  "Judith-D":              { col1: ["SureShot IS", "TrueSight IS"], col2: ["Army of One"], col3: ["Spray and Play"], col4: ["Speed Reload"] },
  "Kumakatok HC-4":        { col1: ["SureShot IS", "TrueSight IS"], col2: ["Luck in the Chamber"], col3: ["Extended Mag"], col4: ["Firefly"] },
  "The Lingering Song":    { col1: ["Iron Lordly Sights"], col2: ["Firefly"], col3: ["Reinforced Barrel", "Rifled Barrel"], col4: ["High Caliber Rounds"] },
  "Lord High Fixer":       { col1: ["SureShot IS", "TrueSight IS"], col2: ["Outlaw"], col3: ["Explosive Rounds"], col4: ["Luck in the Chamber"] },
  "The Palindrome":        { col1: ["SureShot IS", "TrueSight IS"], col2: ["Spray and Play"], col3: ["High Caliber Rounds"], col4: ["Luck in the Chamber"] },
  "The Revelator":         { col1: ["SureShot IS", "TrueSight IS"], col2: ["Spray and Play"], col3: ["Extended Mag"], col4: ["Army of One"] },
  "Stolen Pride":          { col1: ["SureShot IS", "TrueSight IS"], col2: ["Spray and Play"], col3: ["Extended Mag"], col4: ["High Caliber Rounds"] },
  "The Vanity":            { col1: ["SureShot IS", "TrueSight IS"], col2: ["Luck in the Chamber"], col3: ["Extended Mag"], col4: ["Firefly"] },
  "Uffren HC4":            { col1: ["SureShot IS", "TrueSight IS"], col2: ["Luck in the Chamber"], col3: ["Extended Mag"], col4: ["Firefly"] },
  "The Wail":              { col1: ["SureShot IS", "TrueSight IS"], col2: ["Outlaw"], col3: ["Explosive Rounds"], col4: ["Firefly"] },

  // Auto Rifles
  "An Answering Chord":    { col1: ["SPO-28"], col2: ["Perfect Balance"], col3: ["Reinforced Barrel"], col4: ["Spray and Play"] },
  "Antipodal Hindsight":   { col1: ["Reflex"], col2: ["Spray and Play"], col3: ["Speed Reload"], col4: ["Army of One"] },
  "Arminius-D":            { col1: ["SC Holo"], col2: ["Crowd Control"], col3: ["Counterbalance"], col4: ["High Caliber Rounds"] },
  "Assembly II":           { col1: ["Reflex"], col2: ["Extended Mag"], col3: ["Crowd Control"], col4: ["Counterbalance"] },
  "The Continental":       { col1: ["Reflex"], col2: ["Spray and Play"], col3: ["Rifled Barrel"], col4: ["Persistence"] },
  "The Dealbreaker":       { col1: ["SC Holo"], col2: ["Crowd Control"], col3: ["Spray and Play"], col4: ["Rifled Barrel"] },
  "Doctrine of Passing":   { col1: ["FastDraw IS"], col2: ["Persistence"], col3: ["Braced Frame"], col4: ["Counterbalance"] },
  "Does Not Bow":          { col1: ["Red Dot-OAS"], col2: ["Spray and Play"], col3: ["Perfect Balance"], col4: ["Army of One"] },
  "Extremophile 011":      { col1: ["Reflex"], col2: ["Extended Mag"], col3: ["Spray and Play"], col4: ["Persistence"] },
  "Grim Citizen III":      { col1: ["Red Dot-OAS"], col2: ["Crowd Control"], col3: ["Perfect Balance"], col4: ["Army of One"] },
  "Haakon's Hatchet":      { col1: ["Red Dot-OAS"], col2: ["Crowd Control"], col3: ["Perfect Balance"], col4: ["Army of One"] },
  "Her Memory":            { col1: ["Reflex"], col2: ["Spray and Play"], col3: ["Perfect Balance"], col4: ["Army of One"] },
  "Hex Caster ARC":        { col1: ["Red Dot-OAS"], col2: ["Rangefinder"], col3: ["Perfect Balance"], col4: ["Spray and Play"] },
  "Paleocontact JPK-43":   { col1: ["Reflex"], col2: ["Crowd Control"], col3: ["Perfect Balance"], col4: ["Army of One"] },
  "Red Spectre":           { col1: ["Red Dot-OAS"], col2: ["Crowd Control"], col3: ["Perfect Balance"], col4: ["Army of One"] },
  "Shadow Price":          { col1: ["Red Dot-OAS"], col2: ["Crowd Control"], col3: ["Perfect Balance"], col4: ["Army of One"] },
  "Soulstealer's Claw":    { col1: ["Red Dot-OAS"], col2: ["Perfect Balance"], col3: ["Single Point Sling"], col4: ["Spray and Play"] },
  "SUROS ARI-41":          { col1: ["SPO-28"], col2: ["High Caliber Rounds"], col3: ["Rifled Barrel"], col4: ["Spray and Play"] },
  "SUROS ARI-45":          { col1: ["SPO-28"], col2: ["High Caliber Rounds"], col3: ["Rifled Barrel"], col4: ["Spray and Play"] },
  "The Unbent Tree":       { col1: ["Iron Ranged Scope"], col2: ["Perfect Balance"], col3: ["Appended Mag"], col4: ["Counterbalance"] },
  "Vision Stone":          { col1: ["Smart Drift Control"], col2: ["Injection Mold"], col3: ["Hand Loaded"], col4: ["Crowd Control"] },
  "Zarinaea-D":            { col1: ["SC Holo"], col2: ["Crowd Control"], col3: ["Spray and Play"], col4: ["Rifled Barrel"] },
  "Zero-Day Dilemma":      { col1: ["Reflex"], col2: ["Spray and Play"], col3: ["Perfect Balance"], col4: ["Counterbalance"] },

  // Sniper Rifles
  "1000 Yard Stare":       { col1: ["ShortGaze SLH10"], col2: ["Triple Tap"], col3: ["Casket Mag"], col4: ["Spray and Play"] },
  "20/20 AMR7":            { col1: ["ShortGaze SLH10"], col2: ["Unflinching"], col3: ["Skip Rounds"], col4: ["Firefly"] },
  "Antinomy XVI":          { col1: ["ATA Scout"], col2: ["Surplus"], col3: ["Spray and Play"], col4: ["Appended Magazine"] },
  "Aoife Rua-D":           { col1: ["ATA Scout"], col2: ["Surplus"], col3: ["Spray and Play"], col4: ["Appended Magazine"] },
  "Bitter Edge 010":       { col1: ["ShortGaze SLH10"], col2: ["Skip Rounds"], col3: ["Triple Tap"], col4: ["Unflinching"] },
  "But Not Forgotten":     { col1: ["Linear Compensator"], col2: ["Perfect Balance"], col3: ["Explosive Rounds"], col4: ["Triple Tap"] },
  "Deposition VII":        { col1: ["ShortGaze SLH10"], col2: ["Skip Rounds"], col3: ["Triple Tap"], col4: ["Unflinching"] },
  "Devil's Dawn":          { col1: ["Linear Compensator"], col2: ["Life Support"], col3: ["Quickdraw"], col4: ["Firefly"] },
  "Eirene RR4":            { col1: ["Faucon SS1"], col2: ["Triple Tap"], col3: ["Casket Mag"], col4: ["Clown Cartridge"] },
  "Event Horizon":         { col1: ["ShortGaze SLH10"], col2: ["Triple Tap"], col3: ["Casket Mag"], col4: ["Unflinching"] },
  "Extrasolar RR4":        { col1: ["ShortGaze SLH10"], col2: ["Triple Tap"], col3: ["Casket Mag"], col4: ["Spray and Play"] },
  "Her Fury":              { col1: ["ShortGaze SLH10"], col2: ["Triple Tap"], col3: ["Casket Mag"], col4: ["Spray and Play"] },
  "The Laughing Heart":    { col1: ["Linear Compensator"], col2: ["Injection Mold"], col3: ["Explosive Rounds"], col4: ["Triple Tap"] },
  "LDR 5001":              { col1: ["ShortGaze SLH10"], col2: ["Triple Tap"], col3: ["Hand-laid Stock"], col4: ["Unflinching"] },
  "Seventh Sense":         { col1: ["ViewTac SLH20", "Ambush SLH25"], col2: ["Triple Tap"], col3: ["Casket Mag"], col4: ["Unflinching"] },
  "Tamar-D":               { col1: ["ATA Scout"], col2: ["Surplus"], col3: ["Spray and Play"], col4: ["Appended Magazine"] },
  "Tao Hua Yuan":          { col1: ["ShortGaze SLH10"], col2: ["Triple Tap"], col3: ["Casket Mag"], col4: ["Spray and Play"] },
  "Uzume RR4":             { col1: ["Faucon SS1"], col2: ["Triple Tap"], col3: ["Casket Mag"], col4: ["Clown Cartridge"] },
  "Weyloran's March":      { col1: ["ShortGaze SLH10"], col2: ["Triple Tap"], col3: ["Casket Mag"], col4: ["Spray and Play"] },
  "Y-09 Longbow Synthesis":{ col1: ["ShortGaze SLH10"], col2: ["Triple Tap"], col3: ["Casket Mag"], col4: ["Unflinching"] },

  // Shotguns
  "44 Curtain Call":       { col1: ["Linear Compensator", "Accurized Ballistics", "Field Choke"], col2: ["Army of One"], col3: ["Rifled Barrel"], col4: ["Crowd Control"] },
  "Bad Counsel IV":        { col1: ["Aggressive Ballistics"], col2: ["Hammer Forged"], col3: ["Extended Mag"], col4: ["Crowd Control"] },
  "Burden of Proof":       { col1: ["Linear Compensator", "Accurized Ballistics", "Field Choke"], col2: ["Army of One"], col3: ["Reinforced Barrel", "Rifled Barrel"], col4: ["Performance Bonus"] },
  "The Comedian":          { col1: ["Linear Compensator", "Accurized Ballistics", "Field Choke"], col2: ["Crowd Control"], col3: ["Reinforced Barrel", "Rifled Barrel"], col4: ["Performance Bonus"] },
  "Conspiracy Theory-D":   { col1: ["Field Choke"], col2: ["Army of One"], col3: ["Rifled Barrel"], col4: ["Performance Bonus"] },
  "Her Champion":          { col1: ["Linear Compensator", "Accurized Ballistics", "Field Choke"], col2: ["Army of One"], col3: ["Reinforced Barrel", "Rifled Barrel"], col4: ["Crowd Control"] },
  "Jingukogo-D":           { col1: ["Linear Compensator", "Accurized Ballistics", "Field Choke"], col2: ["Rangefinder"], col3: ["Rifled Barrel"], col4: ["Army of One"] },
  "Last-Ditch 001":        { col1: ["CQB Ballistics"], col2: ["Rangefinder"], col3: ["Close and/or Personal", "Close and Personal"], col4: ["Extended Mag"] },
  "Matador 64":            { col1: ["Aggressive Ballistics"], col2: ["Performance Bonus"], col3: ["Reinforced Barrel", "Rifled Barrel"], col4: ["Crowd Control"] },
  "The Next Big Thing":    { col1: ["Linear Compensator", "Accurized Ballistics", "Field Choke"], col2: ["Spray and Play"], col3: ["Rifled Barrel"], col4: ["Army of One"] },
  "Occam's Razor":         { col1: ["Linear Compensator", "Accurized Ballistics", "Field Choke"], col2: ["Army of One"], col3: ["Reinforced Barrel", "Rifled Barrel"], col4: ["Crowd Control"] },
  "Patch-A":               { col1: ["Linear Compensator", "Accurized Ballistics", "Field Choke"], col2: ["Spray and Play"], col3: ["Rifled Barrel"], col4: ["Army of One"] },
  "Party Crasher +1":      { col1: ["Aggressive Ballistics"], col2: ["Army of One"], col3: ["Rifled Barrel"], col4: ["Performance Bonus"] },
  "The Proud Spire":       { col1: ["Linear Compensator"], col2: ["Army of One"], col3: ["Reinforced Barrel", "Rifled Barrel"], col4: ["Performance Bonus"] },
  "Stolen Will":           { col1: ["Linear Compensator", "Accurized Ballistics", "Field Choke"], col2: ["Army of One"], col3: ["Reinforced Barrel", "Rifled Barrel"], col4: ["Performance Bonus"] },
  "Strongbow-D":           { col1: ["Linear Compensator", "Accurized Ballistics", "Field Choke"], col2: ["Rangefinder"], col3: ["Rifled Barrel"], col4: ["Army of One"] },
  "Two to the Morgue":     { col1: ["Linear Compensator", "Accurized Ballistics", "Field Choke"], col2: ["Army of One"], col3: ["Reinforced Barrel", "Rifled Barrel"], col4: ["Performance Bonus"] },
  "Unraveling Thread":     { col1: ["CQB Ballistics"], col2: ["Hammer Forged"], col3: ["Hand Loaded"], col4: ["Rangefinder"] },
  "Winter's End":          { col1: ["Linear Compensator"], col2: ["Appended Mag"], col3: ["Reinforced Barrel", "Rifled Barrel"], col4: ["Army of One"] },

  // Fusion Rifles
  "77 Wizard":             { col1: ["Red Dot-OAS"], col2: ["Spray and Play"], col3: ["Enhanced Battery"], col4: ["Grenadier"] },
  "Ashraven's Flight":     { col1: ["Red Dot-OAS"], col2: ["Spray and Play"], col3: ["Enhanced Battery"], col4: ["Army of One"] },
  "The Branded Lord":      { col1: ["Linear Compensator"], col2: ["Enhanced Battery"], col3: ["Reinforced Barrel"], col4: ["Life Support"] },
  "Darkblade's Spite":     { col1: ["Red Dot-OAS"], col2: ["Army of One"], col3: ["Enhanced Battery"], col4: ["Spray and Play"] },
  "Each New Day":          { col1: ["Reflex"], col2: ["Spray and Play"], col3: ["Enhanced Battery"], col4: ["Rangefinder"] },
  "Ex Astris":             { col1: ["Reflex"], col2: ["Spray and Play"], col3: ["Enhanced Battery"], col4: ["Rangefinder"] },
  "Hitchhiker FR4":        { col1: ["Reflex"], col2: ["Spray and Play"], col3: ["Enhanced Battery"], col4: ["Army of One"] },
  "Long Far Gone":         { col1: ["Reflex"], col2: ["Spray and Play"], col3: ["Enhanced Battery"], col4: ["Army of One"] },
  "Phanta Rei":            { col1: ["Reflex"], col2: ["Spray and Play"], col3: ["Enhanced Battery"], col4: ["Army of One"] },
  "Saladin's Vigil":       { col1: ["Linear Compensator"], col2: ["Enhanced Battery"], col3: ["Reinforced Barrel"], col4: ["Life Support"] },
  "Split Shifter Pro":     { col1: ["Red Dot-OAS"], col2: ["Spray and Play"], col3: ["Enhanced Battery"], col4: ["Army of One"] },
  "Techuen Rage":          { col1: ["Reflex"], col2: ["Spray and Play"], col3: ["Enhanced Battery"], col4: ["Army of One"] },
  "Thesan FR4":            { col1: ["Torch HS2"], col2: ["Spray and Play"], col3: ["Enhanced Battery"], col4: ["Army of One"] },
  "The Vacancy":           { col1: ["Torch HS2"], col2: ["Army of One"], col3: ["Enhanced Battery"], col4: ["Life Support"] },
  "The Vortex":            { col1: ["Reflex"], col2: ["Spray and Play"], col3: ["Enhanced Battery"], col4: ["Army of One"] },
  "The Waiting":           { col1: ["Reflex"], col2: ["Spray and Play"], col3: ["Enhanced Battery"], col4: ["Rangefinder"] },
  "Worlds to Come 001":    { col1: ["Reflex"], col2: ["Spray and Play"], col3: ["Enhanced Battery"], col4: ["Rangefinder"] },

  // Sidearms (same as PvP per guide)
  "Anton's Rule":          { col1: ["SureShot IS", "TrueSight IS"], col2: ["Zen Moment"], col3: ["Hand Loaded"], col4: ["Rangefinder", "Hidden Hand"] },
  "The Binding Blaze":     { col1: ["Iron Lordly Sights"], col2: ["Hand Loaded", "Fitted Stock"], col3: ["High Caliber Rounds"], col4: ["Rangefinder", "Hidden Hand", "Zen Moment"] },
  "Conviction II":         { col1: ["SureShot IS", "TrueSight IS"], col2: ["Zen Moment"], col3: ["Hot Swap"], col4: ["High Caliber Rounds"] },
  "Crow's Eye":            { col1: ["Linear Compensator"], col2: ["Hand Loaded"], col3: ["High Caliber Rounds"], col4: ["Rangefinder"] },
  "Havoc Pigeon":          { col1: ["SureShot IS", "TrueSight IS"], col2: ["Zen Moment"], col3: ["Hot Swap"], col4: ["High Caliber Rounds"] },
  "Impeacher V":           { col1: ["SureShot IS", "TrueSight IS"], col2: ["High Caliber Rounds", "Quickdraw"], col3: ["Hand Loaded"], col4: ["Rangefinder", "Hidden Hand"] },
  "Ironwreath-D":          { col1: ["SureShot IS", "TrueSight IS"], col2: ["Zen Moment"], col3: ["Hot Swap"], col4: ["High Caliber Rounds"] },
  "JabberHakke-D":         { col1: ["SureShot IS", "TrueSight IS"], col2: ["Zen Moment"], col3: ["Hot Swap"], col4: ["High Caliber Rounds"] },
  "Teacup Tempest":        { col1: ["SureShot IS", "TrueSight IS"], col2: ["Zen Moment"], col3: ["High Caliber Rounds"], col4: ["Rangefinder"] },
  "Queen's Choice":        { col1: ["Linear Compensator"], col2: ["Rangefinder", "Zen Moment"], col3: ["High Caliber Rounds"], col4: ["Hot Swap"] },
  "The Wormwood":          { col1: ["SureShot IS", "TrueSight IS"], col2: ["High Caliber Rounds", "Quickdraw"], col3: ["Hand Loaded"], col4: ["Rangefinder", "Hidden Hand"] },

  // Machine Guns
  "Bane of the Taken":     { col1: ["Smooth Ballistics"], col2: ["Spray and Play"], col3: ["High Caliber Rounds"], col4: ["Feeding Frenzy"] },
  "Baron's Ambition":      { col1: ["Accurized Ballistics", "Linear Compensator"], col2: ["Spray and Play"], col3: ["High Caliber Rounds"], col4: ["Feeding Frenzy"] },
  "Bonekruscher":          { col1: ["Linear Compensator"], col2: ["Feeding Frenzy"], col3: ["Perfect Balance"], col4: ["Crowd Control"] },
  "Bretomart's Stand":     { col1: ["Linear Compensator"], col2: ["Spray and Play"], col3: ["High Caliber Rounds"], col4: ["Feeding Frenzy"] },
  "Chaotic Neutral":       { col1: ["Linear Compensator"], col2: ["Feeding Frenzy"], col3: ["Perfect Balance"], col4: ["Crowd Control"] },
  "Diluvian 10/4X":        { col1: ["Linear Compensator"], col2: ["Spray and Play"], col3: ["High Caliber Rounds"], col4: ["Feeding Frenzy"] },
  "First Citizen IX":      { col1: ["Linear Compensator"], col2: ["Feeding Frenzy"], col3: ["High Caliber Rounds"], col4: ["Persistence"] },
  "Ruin Wake":             { col1: ["Linear Compensator"], col2: ["Spray and Play"], col3: ["High Caliber Rounds"], col4: ["Feeding Frenzy"] },
  "Objection IV":          { col1: ["Linear Compensator"], col2: ["Spray and Play"], col3: ["High Caliber Rounds"], col4: ["Feeding Frenzy"] },
  "The Silvered Dread":    { col1: ["Linear Compensator"], col2: ["Spray and Play"], col3: ["Extended Mag"], col4: ["Perfect Balance"] },
  "The Swarm":             { col1: ["Linear Compensator"], col2: ["Spray and Play"], col3: ["High Caliber Rounds"], col4: ["Feeding Frenzy"] },
  "Unending Deluge III":   { col1: ["Linear Compensator"], col2: ["Spray and Play"], col3: ["High Caliber Rounds"], col4: ["Persistence"] },
  "The Variable":          { col1: ["Linear Compensator"], col2: ["Spray and Play"], col3: ["High Caliber Rounds"], col4: ["Feeding Frenzy"] },
  "Zombie Apocalypse WF47":{ col1: ["Linear Compensator", "Accurized Ballistics", "Field Choke"], col2: ["Spray and Play"], col3: ["High Caliber Rounds"], col4: ["Feeding Frenzy"] },

  // Rocket Launchers
  "The Ash Factory":       { col1: ["Warhead Verniers", "Hard Launch"], col2: ["Tripod"], col3: ["Javelin"], col4: ["Grenades and Horseshoes", "Tracking"] },
  "Disassembly Required":  { col1: ["Warhead Verniers", "Hard Launch"], col2: ["Heavy Payload"], col3: ["Javelin"], col4: ["Grenades and Horseshoes", "Tracking"] },
  "The Nightmare":         { col1: ["Warhead Verniers", "Hard Launch"], col2: ["Tripod"], col3: ["Field Scout"], col4: ["Grenades and Horseshoes", "Tracking"] },
  "Something Wicked":      { col1: ["Soft Launch"], col2: ["Grenadier", "Last Resort"], col3: ["Field Scout"], col4: ["Cluster Bomb"] },
  "SUROS JLB-42":          { col1: ["Warhead Verniers", "Hard Launch"], col2: ["Heavy Payload"], col3: ["Grenades and Horseshoes", "Tracking"], col4: ["Javelin"] },
  "SUROS JLB-47":          { col1: ["Warhead Verniers", "Hard Launch"], col2: ["Heavy Payload"], col3: ["Grenades and Horseshoes", "Tracking"], col4: ["Javelin"] },
  "Steel Oracle Z-11":     { col1: ["Warhead Verniers", "Hard Launch"], col2: ["Tripod"], col3: ["Field Scout"], col4: ["Grenades and Horseshoes", "Tracking"] },
  "The Titanium Orchid":   { col1: ["Hard Launch", "Aggressive Launch"], col2: ["Heavy Payload"], col3: ["Speed Reload", "Flared Magwell"], col4: ["Grenades and Horseshoes", "Tracking"] },
  "Tormod's Bellows":      { col1: ["Warhead Verniers", "Hard Launch"], col2: ["Tripod"], col3: ["Heavy Payload"], col4: ["Grenades and Horseshoes", "Tracking"] },
  "Unto Dust 00":          { col1: ["Warhead Verniers", "Hard Launch"], col2: ["Field Scout"], col3: ["Heavy Payload"], col4: ["Grenades and Horseshoes", "Tracking"] },
  "The Vertigo":           { col1: ["Warhead Verniers", "Hard Launch"], col2: ["Heavy Payload"], col3: ["Grenades and Horseshoes", "Tracking"], col4: ["Javelin"] },
  "The Warpath":           { col1: ["Warhead Verniers", "Hard Launch"], col2: ["Field Scout"], col3: ["Javelin"], col4: ["Grenades and Horseshoes", "Tracking"] },
};
