export const RD_PVE = {
  "Angel's Advocate": { source: 'Reddit', col1: ["Reflex"], col2: ["Outlaw"], col3: ["Explosive Rounds"], col4: ["Firefly"] },
  'Badger CCL': { source: 'Reddit', col1: ["Red Dot-OAS"], col2: ["Triple Tap"], col3: ["Explosive Rounds"], col4: ["Army of One"] },
  'Cocytus SR4': { source: 'Reddit', col1: ["Torch HS2"], col2: ["Triple Tap"], col3: ["Extended Mag"], col4: ["Firefly"] },
  "Colovance's Duty": { source: 'Reddit', col1: ["Red Dot-OAS"], col2: ["Triple Tap"], col3: ["Field Scout"], col4: ["Firefly"] },
  'Cryptic Dragon': { source: 'Reddit', col1: ["Red Dot-OAS"], col2: ["Triple Tap"], col3: ["Explosive Rounds"], col4: ["Firefly"] },
  'The Distant Star': { source: 'Reddit', col1: ["Iron Ranged Scope"], col2: ["Triple Tap"], col3: ["Perfect Balance"], col4: ["Extended Mag"] },
  'Hand of Judgement': { source: 'Reddit', col1: ["Red Dot-OAS"], col2: ["Perfect Balance"], col3: ["Explosive Rounds"], col4: ["Firefly"] },
  'The Hero Formula': { source: 'Reddit', col1: ["Reflex"], col2: ["Outlaw"], col3: ["Explosive Rounds"], col4: ["Firefly"] },
  'Keystone 01': { source: 'Reddit', col1: ["Reflex"], col2: ["Triple Tap"], col3: ["Extended Mag"], col4: ["Firefly"] },
  'Lethe Noblesse': { source: 'Reddit', col1: ["Reflex"], col2: ["Triple Tap"], col3: ["Explosive Rounds"], col4: ["Army of One"] },
  'NL Shadow 701X': { source: 'Reddit', col1: ["Red Dot-OAS"], col2: ["Triple Tap"], col3: ["Field Scout"], col4: ["Army of One"] },
  'Not Like the Others': { source: 'Reddit', col1: ["Reflex"], col2: ["Triple Tap"], col3: ["Perfect Balance"], col4: ["Firefly"] },
  'The Saterienne Rapier': { source: 'Reddit', col1: ["Red Dot-OAS"], col2: ["Triple Tap"], col3: ["Field Scout"], col4: ["Army of One"] },
  'SUROS DIS-43': { source: 'Reddit', col1: ["SPO-28"], col2: ["Perfect Balance"], col3: ["Spray and Play"], col4: ["Speed Reload"] },
  'SUROS DIS-47': { source: 'Reddit', col1: ["SPO-28"], col2: ["Perfect Balance"], col3: ["Spray and Play"], col4: ["Speed Reload"] },
  'Treads Upon Stars': { source: 'Reddit', col1: ["Red Dot-OAS"], col2: ["Triple Tap"], col3: ["Field Scout"], col4: ["Army of One"] },
  'Tuonela SR4': { source: 'Reddit', col1: ["Torch HS2"], col2: ["Triple Tap"], col3: ["Extended Mag"], col4: ["Firefly"] },
  'The Wounded': { source: 'Reddit', col1: ["Reflex"], col2: ["Triple Tap"], col3: ["Extended Mag"], col4: ["Firefly"] },
  'Aegis of the Reef': { source: 'Reddit', col1: ["Red Dot-OAS", "SureShot IS"], col2: ["Perfect Balance"], col3: ["High Caliber Rounds"], col4: ["Counterbalance"] },
  'Apple of Discord': { source: 'Reddit', col1: ["SC Holo"], col2: ["Headseeker"], col3: ["Counterbalance"], col4: ["Hand-laid Stock"] },
  'B-29 Party Favor': { source: 'Reddit', col1: ["Reflex"], col2: ["Feeding Frenzy"], col3: ["Perfect Balance"], col4: ["Headseeker"] },
  'The Clever Dragon': { source: 'Reddit', col1: ["Iron Red Dot"], col2: ["Smallbore"], col3: ["High Caliber Rounds"], col4: ["Counterbalance"] },
  'Final Duty': { source: 'Reddit', col1: ["Reflex"], col2: ["Counterbalance"], col3: ["Braced Frame"], col4: ["Feeding Frenzy"] },
  'Grasp of Malok': { source: 'Reddit', col1: ["Red Dot-OAS"], col2: ["Counterbalance"], col3: ["Braced Frame", "Smallbore", "Perfect Balance"], col4: ["Feeding Frenzy"] },
  'Hawksaw': { source: 'Reddit', col1: ["SPO-28"], col2: ["Perfect Balance"], col3: ["Counterbalance"], col4: ["Rifled Barrel"] },
  'Herja-D': { source: 'Reddit', col1: ["SC Holo"], col2: ["Headseeker"], col3: ["Counterbalance"], col4: ["Hand-laid Stock"] },
  'Hopscotch Pilgrim': { source: 'Reddit', col1: ["Red Dot-OAS"], col2: ["Headseeker"], col3: ["Perfect Balance"], col4: ["Feeding Frenzy"] },
  'Lyudmila-D': { source: 'Reddit', col1: ["SC Holo"], col2: ["Headseeker"], col3: ["Counterbalance"], col4: ["Hand-laid Stock"] },
  "Nirwen's Mercy": { source: 'Reddit', col1: ["Red Dot-OAS"], col2: ["Counterbalance"], col3: ["Braced Frame"], col4: ["Feeding Frenzy"] },
  'Parthian Shot': { source: 'Reddit', col1: ["Reflex"], col2: ["Feeding Frenzy"], col3: ["Hand-laid Stock"], col4: ["Headseeker"] },
  'Spare Change .25': { source: 'Reddit', col1: ["Red Dot-OAS"], col2: ["Counterbalance"], col3: ["Braced Frame"], col4: ["Feeding Frenzy"] },
  'SUROS PDX-41': { source: 'Reddit', col1: ["SPO-28"], col2: ["Perfect Balance"], col3: ["Counterbalance"], col4: ["Rifled Barrel", "Smallbore"] },
  'SUROS PDX-45': { source: 'Reddit', col1: ["SPO-28"], col2: ["Perfect Balance"], col3: ["Counterbalance"], col4: ["Rifled Barrel", "Smallbore"] },
  'The Villainy': { source: 'Reddit', col1: ["Red Dot-OAS"], col2: ["Counterbalance"], col3: ["Braced Frame"], col4: ["Feeding Frenzy"] },
  'The Waltz': { source: 'Reddit', col1: ["Reflex"], col2: ["Feeding Frenzy"], col3: ["High Caliber Rounds"], col4: ["Headseeker"] },
  'Byronic Hero': { source: 'Reddit', col1: ["SureShot IS", "TrueSight IS"], col2: ["Spray and Play"], col3: ["Extended Mag"], col4: ["Luck in the Chamber"] },
  'The Devil You Know': { source: 'Reddit', col1: ["SureShot IS", "TrueSight IS"], col2: ["Outlaw"], col3: ["Explosive Rounds"], col4: ["Luck in the Chamber"] },
  'Down and Doubt 00-0': { source: 'Reddit', col1: ["SureShot IS", "TrueSight IS"], col2: ["Luck in the Chamber"], col3: ["Extended Mag"], col4: ["Firefly"] },
  'Eyasluna': { source: 'Reddit', col1: ["SureShot IS", "TrueSight IS"], col2: ["Spray and Play"], col3: ["Extended Mag"], col4: ["Army of One"] },
  "Finnala's Peril": { source: 'Reddit', col1: ["SureShot IS", "TrueSight IS"], col2: ["Spray and Play"], col3: ["Extended Mag"], col4: ["Army of One"] },
  'Free Will III': { source: 'Reddit', col1: ["SureShot IS", "TrueSight IS"], col2: ["Outlaw"], col3: ["Explosive Rounds"], col4: ["Firefly"] },
  'Gaheris-D': { source: 'Reddit', col1: ["SureShot IS", "TrueSight IS"], col2: ["Army of One"], col3: ["Spray and Play"], col4: ["Speed Reload"] },
  'Her Revenge': { source: 'Reddit', col1: ["SureShot IS", "TrueSight IS"], col2: ["Spray and Play"], col3: ["Extended Mag"], col4: ["Army of One"] },
  'How Dare You': { source: 'Reddit', col1: ["SureShot IS", "TrueSight IS"], col2: ["Spray and Play"], col3: ["High Caliber Rounds"], col4: ["Luck in the Chamber"] },
  'Ill Will': { source: 'Reddit', col1: ["SureShot IS", "TrueSight IS"], col2: ["Outlaw"], col3: ["Extended Mag"], col4: ["Luck in the Chamber"] },
  'Imago Loop (Fatebringer Roll)': { source: 'Reddit', col1: ["SureShot IS", "TrueSight IS"], col2: ["Outlaw"], col3: ["Explosive Rounds"], col4: ["Firefly"] },
  'Judith-D': { source: 'Reddit', col1: ["SureShot IS", "TrueSight IS"], col2: ["Army of One"], col3: ["Spray and Play"], col4: ["Speed Reload"] },
  'Kumakatok HC-4': { source: 'Reddit', col1: ["SureShot IS", "TrueSight IS"], col2: ["Luck in the Chamber"], col3: ["Extended Mag"], col4: ["Firefly"] },
  'The Lingering Song': { source: 'Reddit', col1: ["Iron Lordly Sights"], col2: ["Firefly"], col3: ["Reinforced Barrel", "Rifled Barrel"], col4: ["High Caliber Rounds"] },
  'Lord High Fixer': { source: 'Reddit', col1: ["SureShot IS", "TrueSight IS"], col2: ["Outlaw"], col3: ["Explosive Rounds"], col4: ["Luck in the Chamber"] },
  'The Palindrome': { source: 'Reddit', col1: ["SureShot IS", "TrueSight IS"], col2: ["Spray and Play"], col3: ["High Caliber Rounds"], col4: ["Luck in the Chamber"] },
  'The Revelator': { source: 'Reddit', col1: ["SureShot IS", "TrueSight IS"], col2: ["Spray and Play"], col3: ["Extended Mag"], col4: ["Army of One"] },
  'Stolen Pride': { source: 'Reddit', col1: ["SureShot IS", "TrueSight IS"], col2: ["Spray and Play"], col3: ["Extended Mag"], col4: ["High Caliber Rounds"] },
  'The Vanity': { source: 'Reddit', col1: ["SureShot IS", "TrueSight IS"], col2: ["Luck in the Chamber"], col3: ["Extended Mag"], col4: ["Firefly"] },
  'Uffern HC4': { source: 'Reddit', col1: ["SureShot IS", "TrueSight IS"], col2: ["Luck in the Chamber"], col3: ["Extended Mag"], col4: ["Firefly"] },
  'The Wail': { source: 'Reddit', col1: ["SureShot IS", "TrueSight IS"], col2: ["Outlaw"], col3: ["Explosive Rounds"], col4: ["Firefly"] },
  'An Answering Chord': { source: 'Reddit', col1: ["SPO-28"], col2: ["Perfect Balance"], col3: ["Reinforced Barrel"], col4: ["Spray and Play"] },
  'Antipodal Hindsight': { source: 'Reddit', col1: ["Reflex"], col2: ["Spray and Play"], col3: ["Speed Reload"], col4: ["Army of One"] },
  'Arminius-D': { source: 'Reddit', col1: ["SC Holo"], col2: ["Crowd Control"], col3: ["Counterbalance"], col4: ["High Caliber Rounds"] },
  'Assembly II': { source: 'Reddit', col1: ["Reflex"], col2: ["Extended Mag"], col3: ["Crowd Control"], col4: ["Counterbalance"] },
  'The Continental': { source: 'Reddit', col1: ["Reflex"], col2: ["Spray and Play"], col3: ["Rifled Barrel"], col4: ["Persistence"] },
  'The Dealbreaker': { source: 'Reddit', col1: ["SC Holo"], col2: ["Crowd Control"], col3: ["Spray and Play"], col4: ["Rifled Barrel"] },
  'Does Not Bow': { source: 'Reddit', col1: ["Red Dot-OAS"], col2: ["Spray and Play"], col3: ["Perfect Balance"], col4: ["Army of One"] },
  'Extremophile 011': { source: 'Reddit', col1: ["Reflex"], col2: ["Extended Mag"], col3: ["Spray and Play"], col4: ["Persistence"] },
  'Grim Citizen III': { source: 'Reddit', col1: ["Red Dot-OAS"], col2: ["Crowd Control"], col3: ["Perfect Balance"], col4: ["Army of One"] },
  "Haakon's Hatchet": { source: 'Reddit', col1: ["Red Dot-OAS"], col2: ["Crowd Control"], col3: ["Perfect Balance"], col4: ["Army of One"] },
  'Her Memory': { source: 'Reddit', col1: ["Reflex"], col2: ["Spray and Play"], col3: ["Perfect Balance"], col4: ["Army of One"] },
  'Hex Caster ARC': { source: 'Reddit', col1: ["Red Dot-OAS"], col2: ["Rangefinder"], col3: ["Perfect Balance"], col4: ["Spray and Play"] },
  'Paleocontact JPK-43': { source: 'Reddit', col1: ["Reflex"], col2: ["Crowd Control"], col3: ["Perfect Balance"], col4: ["Army of One"] },
  'Red Spectre': { source: 'Reddit', col1: ["Red Dot-OAS"], col2: ["Crowd Control"], col3: ["Perfect Balance"], col4: ["Army of One"] },
  'Shadow Price': { source: 'Reddit', col1: ["Red Dot-OAS"], col2: ["Crowd Control"], col3: ["Perfect Balance"], col4: ["Army of One"] },
  "Soulstealer's Claw": { source: 'Reddit', col1: ["Red Dot-OAS"], col2: ["Perfect Balance"], col3: ["Single Point Sling"], col4: ["Spray and Play"] },
  'SUROS ARI-41': { source: 'Reddit', col1: ["SPO-28"], col2: ["High Caliber Rounds"], col3: ["Rifled Barrel"], col4: ["Spray and Play"] },
  'SUROS ARI-45': { source: 'Reddit', col1: ["SPO-28"], col2: ["High Caliber Rounds"], col3: ["Rifled Barrel"], col4: ["Spray and Play"] },
  'The Unbent Tree': { source: 'Reddit', col1: ["Iron Ranged Scope"], col2: ["Perfect Balance"], col3: ["Appended Mag"], col4: ["Counterbalance"] },
  'Vision Stone': { source: 'Reddit', col1: ["Smart Drift Control"], col2: ["Injection Mold"], col3: ["Hand Loaded"], col4: ["Crowd Control"] },
  'Zarinaea-D': { source: 'Reddit', col1: ["SC Holo"], col2: ["Crowd Control"], col3: ["Spray and Play"], col4: ["Rifled Barrel"] },
  'Zero-Day Dilemma': { source: 'Reddit', col1: ["Reflex"], col2: ["Spray and Play"], col3: ["Perfect Balance"], col4: ["Counterbalance"] },
  '1000 Yard Stare': { source: 'Reddit', col1: ["ShortGaze SLH10"], col2: ["Triple Tap"], col3: ["Casket Mag"], col4: ["Spray and Play"] },
  '20/20 AMR7': { source: 'Reddit', col1: ["ShortGaze SLH10"], col2: ["Unflinching"], col3: ["Skip Rounds"], col4: ["Firefly"] },
  'Antinomy XVI': { source: 'Reddit', col1: ["ATA Scout"], col2: ["Surplus"], col3: ["Spray and Play"], col4: ["Appended Magazine"] },
  'Aoife Rua-D': { source: 'Reddit', col1: ["ATA Scout"], col2: ["Surplus"], col3: ["Spray and Play"], col4: ["Appended Magazine"] },
  'Bitter Edge 010': { source: 'Reddit', col1: ["ShortGaze SLH10"], col2: ["Skip Rounds"], col3: ["Triple Tap"], col4: ["Firefly"] },
  'But Not Forgotten': { source: 'Reddit', col1: ["Linear Compensator"], col2: ["Perfect Balance"], col3: ["Explosive Rounds"], col4: ["Triple Tap"] },
  'Deposition VII': { source: 'Reddit', col1: ["ShortGaze SLH10"], col2: ["Skip Rounds"], col3: ["Triple Tap"], col4: ["Firefly"] },
  "Devil's Dawn": { source: 'Reddit', col1: ["Linear Compensator"], col2: ["Life Support"], col3: ["Quickdraw"], col4: ["Firefly"] },
  'Eirene RR4': { source: 'Reddit', col1: ["Faucon SS1"], col2: ["Triple Tap"], col3: ["Casket Mag"], col4: ["Clown Cartridge"] },
  'Event Horizon': { source: 'Reddit', col1: ["ShortGaze SLH10"], col2: ["Triple Tap"], col3: ["Casket Mag"], col4: ["Firefly"] },
  'Extrasolar RR4': { source: 'Reddit', col1: ["ShortGaze SLH10"], col2: ["Triple Tap"], col3: ["Casket Mag"], col4: ["Spray and Play", "Firefly"] },
  'Her Fury': { source: 'Reddit', col1: ["ShortGaze SLH10"], col2: ["Triple Tap"], col3: ["Casket Mag"], col4: ["Spray and Play"] },
  'The Laughing Heart': { source: 'Reddit', col1: ["Linear Compensator"], col2: ["Injection Mold"], col3: ["Explosive Rounds"], col4: ["Triple Tap"] },
  'LDR 5001': { source: 'Reddit', col1: ["ShortGaze SLH10"], col2: ["Triple Tap"], col3: ["Hand-laid Stock"], col4: ["Firefly"] },
  'Seventh Sense': { source: 'Reddit', col1: ["ViewTac SLH20", "Ambush SLH25"], col2: ["Triple Tap"], col3: ["Casket Mag"], col4: ["Firefly"] },
  'Tamar-D': { source: 'Reddit', col1: ["ATA Scout"], col2: ["Surplus"], col3: ["Spray and Play"], col4: ["Appended Magazine"] },
  'Tao Hua Yuan': { source: 'Reddit', col1: ["ShortGaze SLH10"], col2: ["Triple Tap"], col3: ["Casket Mag"], col4: ["Spray and Play"] },
  'Uzume RR4': { source: 'Reddit', col1: ["Faucon SS1"], col2: ["Triple Tap"], col3: ["Casket Mag"], col4: ["Clown Cartridge"] },
  "Weyloran's March": { source: 'Reddit', col1: ["ShortGaze SLH10"], col2: ["Triple Tap"], col3: ["Casket Mag"], col4: ["Spray and Play"] },
  'Y-09 Longbow Synthesis': { source: 'Reddit', col1: ["ShortGaze SLH10"], col2: ["Triple Tap"], col3: ["Casket Mag"], col4: ["Firefly"] },
  '44 Curtain Call': { source: 'Reddit', col1: ["Linear Compensator", "Accurized Ballistics", "Field Choke"], col2: ["Army of One"], col3: ["Rifled Barrel"], col4: ["Crowd Control"] },
  'Bad Counsel IV': { source: 'Reddit', col1: ["Aggressive Ballistics"], col2: ["Hammer Forged"], col3: ["Extended Mag"], col4: ["Crowd Control"] },
  'Burden of Proof XI': { source: 'Reddit', col1: ["Linear Compensator", "Accurized Ballistics", "Field Choke"], col2: ["Army of One"], col3: ["Reinforced Barrel", "Rifled Barrel"], col4: ["Performance Bonus"] },
  'The Comedian': { source: 'Reddit', col1: ["Linear Compensator", "Accurized Ballistics", "Field Choke"], col2: ["Crowd Control"], col3: ["Reinforced Barrel", "Rifled Barrel"], col4: ["Performance Bonus"] },
  'Conspiracy Theory-D': { source: 'Reddit', col1: ["Field Choke"], col2: ["Army of One"], col3: ["Rifled Barrel"], col4: ["Performance Bonus"] },
  'Her Champion': { source: 'Reddit', col1: ["Linear Compensator", "Accurized Ballistics", "Field Choke"], col2: ["Army of One"], col3: ["Reinforced Barrel", "Rifled Barrel"], col4: ["Crowd Control"] },
  'Jingukogo-D': { source: 'Reddit', col1: ["Linear Compensator", "Accurized Ballistics", "Field Choke"], col2: ["Rangefinder"], col3: ["Rifled Barrel"], col4: ["Army of One"] },
  'Last-Ditch 001': { source: 'Reddit', col1: ["CQB Ballistics"], col2: ["Rangefinder"], col3: ["Close and/or Personal", "Close and Personal"], col4: ["Extended Mag"] },
  'Matador 64': { source: 'Reddit', col1: ["Aggressive Ballistics"], col2: ["Performance Bonus"], col3: ["Reinforced Barrel", "Rifled Barrel"], col4: ["Crowd Control"] },
  'The Next Big Thing': { source: 'Reddit', col1: ["Linear Compensator", "Accurized Ballistics", "Field Choke"], col2: ["Spray and Play"], col3: ["Rifled Barrel"], col4: ["Army of One"] },
  "Occam's Razor": { source: 'Reddit', col1: ["Linear Compensator", "Accurized Ballistics", "Field Choke"], col2: ["Army of One"], col3: ["Reinforced Barrel", "Rifled Barrel"], col4: ["Crowd Control"] },
  'Patch-A': { source: 'Reddit', col1: ["Linear Compensator", "Accurized Ballistics", "Field Choke"], col2: ["Spray and Play"], col3: ["Rifled Barrel"], col4: ["Army of One"] },
  'Party Crasher +1': { source: 'Reddit', col1: ["Aggressive Ballistics"], col2: ["Army of One"], col3: ["Rifled Barrel"], col4: ["Performance Bonus"] },
  'The Proud Spire': { source: 'Reddit', col1: ["Linear Compensator"], col2: ["Army of One"], col3: ["Reinforced Barrel", "Rifled Barrel"], col4: ["Performance Bonus"] },
  'Stolen Will': { source: 'Reddit', col1: ["Linear Compensator", "Accurized Ballistics", "Field Choke"], col2: ["Army of One"], col3: ["Reinforced Barrel", "Rifled Barrel"], col4: ["Performance Bonus"] },
  'Strongbow-D': { source: 'Reddit', col1: ["Linear Compensator", "Accurized Ballistics", "Field Choke"], col2: ["Rangefinder"], col3: ["Rifled Barrel"], col4: ["Army of One"] },
  'Two to the Morgue': { source: 'Reddit', col1: ["Linear Compensator", "Accurized Ballistics", "Field Choke"], col2: ["Army of One"], col3: ["Reinforced Barrel", "Rifled Barrel"], col4: ["Performance Bonus"] },
  'Unraveling Thread': { source: 'Reddit', col1: ["CQB Ballistics"], col2: ["Hammer Forged"], col3: ["Hand Loaded"], col4: ["Rangefinder"] },
  "Winter's End": { source: 'Reddit', col1: ["Linear Compensator"], col2: ["Appended Mag"], col3: ["Reinforced Barrel", "Rifled Barrel"], col4: ["Army of One"] },
  '77 Wizard': { source: 'Reddit', col1: ["Red Dot-OAS"], col2: ["Spray and Play"], col3: ["Enhanced Battery"], col4: ["Grenadier"] },
  "Ashraven's Flight": { source: 'Reddit', col1: ["Red Dot-OAS"], col2: ["Spray and Play"], col3: ["Enhanced Battery"], col4: ["Army of One"] },
  'The Branded Lord': { source: 'Reddit', col1: ["Linear Compensator"], col2: ["Enhanced Battery"], col3: ["Reinforced Barrel"], col4: ["Life Support"] },
  "Darkblade's Spite": { source: 'Reddit', col1: ["Red Dot-OAS"], col2: ["Army of One"], col3: ["Enhanced Battery"], col4: ["Spray and Play"] },
  'Each New Day': { source: 'Reddit', col1: ["Reflex"], col2: ["Spray and Play"], col3: ["Enhanced Battery"], col4: ["Rangefinder"] },
  'Ex Astris': { source: 'Reddit', col1: ["Reflex"], col2: ["Spray and Play"], col3: ["Enhanced Battery"], col4: ["Rangefinder"] },
  'Hitchhiker FR4': { source: 'Reddit', col1: ["Reflex"], col2: ["Spray and Play"], col3: ["Enhanced Battery"], col4: ["Army of One"] },
  'Long Far Gone': { source: 'Reddit', col1: ["Reflex"], col2: ["Spray and Play"], col3: ["Enhanced Battery"], col4: ["Army of One"] },
  'Phanta Rei': { source: 'Reddit', col1: ["Reflex"], col2: ["Spray and Play"], col3: ["Enhanced Battery"], col4: ["Army of One"] },
  "Saladin's Vigil": { source: 'Reddit', col1: ["Linear Compensator"], col2: ["Enhanced Battery"], col3: ["Reinforced Barrel"], col4: ["Life Support"] },
  'Split Shifter Pro': { source: 'Reddit', col1: ["Red Dot-OAS"], col2: ["Spray and Play"], col3: ["Enhanced Battery"], col4: ["Army of One"] },
  'Techuen Rage': { source: 'Reddit', col1: ["Reflex"], col2: ["Spray and Play"], col3: ["Enhanced Battery"], col4: ["Army of One"] },
  'Thesan FR4': { source: 'Reddit', col1: ["Torch HS2"], col2: ["Spray and Play"], col3: ["Enhanced Battery"], col4: ["Army of One"] },
  'The Vacancy': { source: 'Reddit', col1: ["Torch HS2"], col2: ["Army of One"], col3: ["Enhanced Battery"], col4: ["Life Support"] },
  'The Vortex': { source: 'Reddit', col1: ["Reflex"], col2: ["Spray and Play"], col3: ["Enhanced Battery"], col4: ["Army of One"] },
  'The Waiting': { source: 'Reddit', col1: ["Reflex"], col2: ["Spray and Play"], col3: ["Enhanced Battery"], col4: ["Rangefinder"] },
  'Worlds to Come 001': { source: 'Reddit', col1: ["Reflex"], col2: ["Spray and Play"], col3: ["Enhanced Battery"], col4: ["Rangefinder"] },
  "Anton's Rule": { source: 'Reddit', col1: ["SureShot IS", "TrueSight IS"], col2: ["Zen Moment"], col3: ["Hand Loaded"], col4: ["Rangefinder", "Hidden Hand"] },
  'The Binding Blaze': { source: 'Reddit', col1: ["Iron Lordly Sights"], col2: ["Hand Loaded", "Fitted Stock"], col3: ["High Caliber Rounds"], col4: ["Rangefinder", "Hidden Hand", "Zen Moment"] },
  'Conviction II': { source: 'Reddit', col1: ["SureShot IS", "TrueSight IS"], col2: ["Zen Moment"], col3: ["Hot Swap"], col4: ["High Caliber Rounds"] },
  "Crow's Eye": { source: 'Reddit', col1: ["Linear Compensator"], col2: ["Hand Loaded"], col3: ["High Caliber Rounds"], col4: ["Rangefinder"] },
  'Havoc Pigeon': { source: 'Reddit', col1: ["SureShot IS", "TrueSight IS"], col2: ["Zen Moment"], col3: ["Hot Swap"], col4: ["High Caliber Rounds"] },
  'Impeacher V': { source: 'Reddit', col1: ["SureShot IS", "TrueSight IS"], col2: ["High Caliber Rounds", "Quickdraw"], col3: ["Hand Loaded"], col4: ["Rangefinder", "Hidden Hand"] },
  'Ironwreath-D': { source: 'Reddit', col1: ["SureShot IS", "TrueSight IS"], col2: ["Zen Moment"], col3: ["Hot Swap"], col4: ["High Caliber Rounds"] },
  'JabberHakke-D': { source: 'Reddit', col1: ["SureShot IS", "TrueSight IS"], col2: ["Zen Moment"], col3: ["Hot Swap"], col4: ["High Caliber Rounds"] },
  'Teacup Tempest': { source: 'Reddit', col1: ["SureShot IS", "TrueSight IS"], col2: ["Zen Moment"], col3: ["High Caliber Rounds"], col4: ["Rangefinder"] },
  "Queen's Choice": { source: 'Reddit', col1: ["Linear Compensator"], col2: ["Rangefinder", "Zen Moment"], col3: ["High Caliber Rounds"], col4: ["Hot Swap"] },
  'The Wormwood': { source: 'Reddit', col1: ["SureShot IS", "TrueSight IS"], col2: ["High Caliber Rounds", "Quickdraw"], col3: ["Hand Loaded"], col4: ["Rangefinder", "Hidden Hand"] },
  'Bane of the Taken': { source: 'Reddit', col1: ["Smooth Ballistics"], col2: ["Spray and Play"], col3: ["High Caliber Rounds"], col4: ["Feeding Frenzy"] },
  "Baron's Ambition": { source: 'Reddit', col1: ["Accurized Ballistics", "Linear Compensator"], col2: ["Spray and Play"], col3: ["High Caliber Rounds"], col4: ["Feeding Frenzy"] },
  'Bonekruscher': { source: 'Reddit', col1: ["Linear Compensator"], col2: ["Feeding Frenzy"], col3: ["Perfect Balance"], col4: ["Crowd Control"] },
  "Bretomart's Stand": { source: 'Reddit', col1: ["Linear Compensator"], col2: ["Spray and Play"], col3: ["High Caliber Rounds"], col4: ["Feeding Frenzy"] },
  'Chaotic Neutral': { source: 'Reddit', col1: ["Linear Compensator"], col2: ["Feeding Frenzy"], col3: ["Perfect Balance"], col4: ["Crowd Control"] },
  'Diluvian 10/4X': { source: 'Reddit', col1: ["Linear Compensator"], col2: ["Spray and Play"], col3: ["High Caliber Rounds"], col4: ["Feeding Frenzy"] },
  'First Citizen IX': { source: 'Reddit', col1: ["Linear Compensator"], col2: ["Feeding Frenzy"], col3: ["High Caliber Rounds"], col4: ["Persistence"] },
  'Ruin Wake': { source: 'Reddit', col1: ["Linear Compensator"], col2: ["Spray and Play"], col3: ["High Caliber Rounds"], col4: ["Feeding Frenzy"] },
  'Objection IV': { source: 'Reddit', col1: ["Linear Compensator"], col2: ["Spray and Play"], col3: ["High Caliber Rounds"], col4: ["Feeding Frenzy"] },
  'The Silvered Dread': { source: 'Reddit', col1: ["Linear Compensator"], col2: ["Spray and Play"], col3: ["Extended Mag"], col4: ["Perfect Balance"] },
  'The Swarm': { source: 'Reddit', col1: ["Linear Compensator"], col2: ["Spray and Play"], col3: ["High Caliber Rounds"], col4: ["Feeding Frenzy"] },
  'Unending Deluge III': { source: 'Reddit', col1: ["Linear Compensator"], col2: ["Spray and Play"], col3: ["High Caliber Rounds"], col4: ["Persistence"] },
  'The Variable': { source: 'Reddit', col1: ["Linear Compensator"], col2: ["Spray and Play"], col3: ["High Caliber Rounds"], col4: ["Feeding Frenzy"] },
  'Zombie Apocalypse WF47': { source: 'Reddit', col1: ["Linear Compensator", "Accurized Ballistics", "Field Choke"], col2: ["Spray and Play"], col3: ["High Caliber Rounds"], col4: ["Feeding Frenzy"] },
  'The Ash Factory': { source: 'Reddit', col1: ["Warhead Verniers", "Hard Launch"], col2: ["Tripod"], col3: ["Javelin"], col4: ["Grenades and Horseshoes", "Tracking"] },
  'Disassembly Required': { source: 'Reddit', col1: ["Warhead Verniers", "Hard Launch"], col2: ["Heavy Payload"], col3: ["Javelin"], col4: ["Grenades and Horseshoes", "Tracking"] },
  'The Nightmare': { source: 'Reddit', col1: ["Warhead Verniers", "Hard Launch"], col2: ["Tripod"], col3: ["Field Scout"], col4: ["Grenades and Horseshoes", "Tracking"] },
  'Something Wicked': { source: 'Reddit', col1: ["Warhead Verniers", "Hard Launch"], col2: ["Battle Runner"], col3: ["Heavy Payload"], col4: ["Grenades and Horseshoes", "Tracking"] },
  'SUROS JLB-42': { source: 'Reddit', col1: ["Warhead Verniers", "Hard Launch"], col2: ["Heavy Payload"], col3: ["Grenades and Horseshoes", "Tracking"], col4: ["Javelin"] },
  'SUROS JLB-47': { source: 'Reddit', col1: ["Warhead Verniers", "Hard Launch"], col2: ["Heavy Payload"], col3: ["Grenades and Horseshoes", "Tracking"], col4: ["Javelin"] },
  'Steel Oracle Z-11': { source: 'Reddit', col1: ["Warhead Verniers", "Hard Launch"], col2: ["Tripod"], col3: ["Field Scout"], col4: ["Grenades and Horseshoes", "Tracking"] },
  'The Titanium Orchid': { source: 'Reddit', col1: ["Hard Launch", "Aggressive Launch"], col2: ["Heavy Payload"], col3: ["Speed Reload", "Flared Magwell"], col4: ["Grenades and Horseshoes", "Tracking"] },
  "Tormod's Bellows": { source: 'Reddit', col1: ["Warhead Verniers", "Hard Launch"], col2: ["Tripod"], col3: ["Heavy Payload"], col4: ["Grenades and Horseshoes", "Tracking"] },
  'Unto Dust 00': { source: 'Reddit', col1: ["Warhead Verniers", "Hard Launch"], col2: ["Field Scout"], col3: ["Heavy Payload"], col4: ["Grenades and Horseshoes", "Tracking"] },
  'The Vertigo': { source: 'Reddit', col1: ["Warhead Verniers", "Hard Launch"], col2: ["Heavy Payload"], col3: ["Grenades and Horseshoes", "Tracking"], col4: ["Javelin"] },
  'The Warpath': { source: 'Reddit', col1: ["Warhead Verniers", "Hard Launch"], col2: ["Field Scout"], col3: ["Javelin"], col4: ["Grenades and Horseshoes", "Tracking"] },
};
